---
language: python
cache: pip
python: "3.7"
env:
  # run against latest version
  - ANSIBLE_VERSION=latest

# Use the new container infrastructure
sudo: false

# Install pip
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible and dependencies
  - pip install ansible --upgrade
  - pip install ansible-lint requests --upgrade

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/requirements/:../' > ansible.cfg

script:
  # Run ansible-lint
  - ansible-lint .

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/